[package]
name = "rs_cutter"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = {version = "54.3.1", features = ["pyarrow"]}
chrono = "0.4.40"
pyo3 = "0.23.3"
thiserror = "2.0.12"
pyo3-arrow = "0.7"
rayon = "1.10.0"

[lib]
name = "rs_cutter"
crate-type = ["cdylib"]
path = "src/lib.rs"
