[package]
name = "rs_cutter"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = {version = "54.3.0", features = ["pyarrow"]}
chrono = "0.4.40"
pyo3 = { version = "^0.23.1", features = ["extension-module"] }

[lib]
name = "rs_cutter"
crate-type = ["cdylib"]
path = "src/lib.rs"