from typing import Dict
import pyarrow as pa

class RsCutter:
    def __init__(self, tables: Dict[str, pa.Table]) -> None: ...
    def total_row_count(self) -> int: ...

def to_uppercase(input: str) -> str: ...
