from datetime import datetime
from typing import Dict
import pyarrow as pa

class RsCutter:
    def __init__(self, tables: Dict[str, pa.Table]) -> None: ...
    def total_row_count(self) -> int: ...
    def slice(self, start: datetime | None, end: datetime | None) -> Dict[str, pa.Table]:...

def to_uppercase(input: str) -> str: ...
